services:
    web-app:
        build:
            context: ./backend
        ports:
            - "8000:8000"
        volumes:
            - ./backend:/backend

        environment:
            - DB_HOST=database
            - DB_NAME=namedatabase
            - DB_USER=postgres
            - DB_PASS=postgres

        # command: >
        #     sh -c "python manage.py runserver 0.0.0.0:8000"

        depends_on:
            - database
            - redis

    redis:
        image: redis:7.0.5-alpine
        hostname: redis

    database:
        image: postgres:15-alpine
        environment:
            - POSTGRES_DB=namedatabase
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres

    react-app:
        image: docker-react-i
        build:
            context: ./frontend/
        ports:
            - 3000:3000
